# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: reginaldo-builds.Posterizador
PackageVersion: 1.0.1
PackageLocale: pt-BR
Publisher: reginaldo-builds
PackageName: Posterizador
License: Licença do MIT
ShortDescription: Posterizador Setup
ManifestType: defaultLocale
ManifestVersion: 1.12.0
